name: Refresh Validate Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
      
    - name: Run data update script
      run: |
        python -m mapswipe.workflows.validate_preprocess
      
    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    
    - name: Commit and push changes
      run: |
        git add mapswipe/data/
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update data on $(date +'%Y-%m-%d')"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
